title: Stackbit Azimuth Theme
baseurl: /
permalink: '/:title/'
palette: blue
header:
  has_nav: true
  logo_img: /images/screenshot-from-2019-11-04-12-13-47.png
  menu:
    actions:
      - label: Sign Up
        url: /signup
  title: Azimuth
footer:
  content: 'Copyright 2016 '
  has_nav: true
  has_social: true
  has_subscribe: true
  links:
    - new_window: true
      text: Made with Stackbit
      url: 'https://www.stackbit.com'
  logo_img: /images/nexastack-brand.png
  nav_title: Explore Us
  social_title: ''
  subscribe_content: >-
    NexaStack provides DevOps as a service and Unified DevOps platform used to
    Automate,Monitor & Analyze the secure application Delivery Pipeline
  subscribe_title: 'Contact Us: 978167389'
  tagline: NexaStack
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
